networks:
  deploy-guide-dev:
    driver: bridge
services:
  coursework:
    environment:
      - ConnectionString=Server=postgres;Port=5432;Database=fileDb;Username=postgres;Password=Ans13042002
      - ASPNETCORE_ENVIRONMENT=Development
    image: coursework
    build:
      context: .
      dockerfile: CourseWork/Dockerfile
    ports: [ 8080:8080 ]
    networks:
      - deploy-guide-dev
    volumes:
        - ./app_data:/var/lib/app/data/  # Привязка тома для файлов
    depends_on: [ postgres ]
  postgres:
    image: postgres:16
    # set shared memory limit when using docker-compose
    shm_size: 256mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: Ans13042002
      POSTGRES_USER: postgres
      POSTGRES_DB: fileDb
    ports :
      - "5434:5432"
    networks:
      - deploy-guide-dev
    volumes: [ "./pg_data:/var/lib/postgresql/data/" ]
